services:
  sssp-report:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8501:8501
    restart: unless-stopped
    #command: streamlit run app.py --server.port 8501
